#!/bin/bash
# Put this file and runpigsty at /root/.
# Then create a cron job to test it on every 5 minutes.
# crontab -e
# */5 * * * * /root/chkpigstylog
#
# Check if "Error: " in pigsty.log or not.  If yes, start Pigsty again.
STRING="Error: "
if grep -R "$STRING" /var/log/pigsty.log
then
	/root/runpigsty
fi


